---
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- include_tasks: install-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: install-RedHat.yml
  when: ansible_os_family == 'RedHat'

- import_tasks: ssh.yml

- import_tasks: sudo.yml

- include_tasks: user.yml
  when: create_user == True

- include_tasks: firewall-Debian.yml
  when: ( ansible_os_family == 'Debian' ) and ( setup_firewall == True )

  - include_tasks: firewall-RedHat.yml
  when: ( ansible_os_family == 'RedHat' ) and ( setup_firewall == True )
